services:
  redis_alilmhub:
    image: redis:7
    container_name: redis_alilmhub_dev
    ports:
      - "6381:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  alilmhub-backend:
    build:
      context: ./alilmhub_backend
      dockerfile: Dockerfile.dev
    container_name: alilmhub-backend_dev
    ports:
      - "5016:5014"
    env_file:
      - ./alilmhub_backend/.env.development
    volumes:
      - ./alilmhub_backend:/app
      - node_modules:/app/node_modules
    depends_on:
      redis_alilmhub:
        condition: service_healthy
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

volumes:
  node_modules:
