services:
  redis_alilmhub:
    image: redis:7
    container_name: redis_alilmhub_dev
    ports:
      - "6381:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  alilmhub-backend:
    build:
      context: ./alilmhub_backend
      dockerfile: Dockerfile.dev
    container_name: alilmhub-backend_dev
    ports:
      - "5016:5014"
    env_file:
      - ./alilmhub_backend/.env.development
    volumes:
      - ./alilmhub_backend:/app
      - node_modules:/app/node_modules    
      - ./logs:/logs
    depends_on:
      redis_alilmhub:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  # Elasticsearch service
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch_alilmhub_dev
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.type=single-node"
    volumes:
      - elasticsearch_data_dev:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Kibana Service
  kibana:
    image: kibana:7.9.2
    container_name: kibana_alilmhub_dev
    restart: always
    depends_on: 
      - elasticsearch 
    ports: 
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200" 


volumes:
  node_modules:
  elasticsearch_data_dev:
